[project]
name = "lyricsipsum"
version = "1.1.6"
description = "Generates Lorem Ipsum text using song lyrics"
authors = [{ name = "Steve Scholnick", email = "scholnicks@gmail.com" }]
requires-python = ">=3.13"
readme = "README.md"
license = "MIT"
keywords = [
    "lorem",
    "ipsum",
    "text",
    "generator",
    "lyrics",
    "utility",
    "command-line",
    "cli",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Topic :: Utilities",
]
dependencies = [
    "docopt-ng (>=0.9.0,<0.10.0)",
    "lyricsgenius (>=3.7.2,<4.0.0)",
]
license-files = ["LICENSE"]

[project.urls]
homepage = "https://pypi.org/project/lyricsipsum/"
repository = "https://github.com/scholnicks/lyricsipsum/"
issues = "https://github.com/scholnicks/lyricsipsum/issues"

[project.scripts]
lyricsipsum = "lyricsipsum.__main__:main"

[tool.hatch.build.targets.sdist]
include = ["src/lyricsipsum"]

[tool.hatch.build.targets.wheel]
include = ["src/lyricsipsum"]

[tool.hatch.build.targets.wheel.sources]
"src/lyricsipsum" = "lyricsipsum"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
